apiVersion: v1
kind: Service   
metadata:
  name: web-flask-svc
  labels:
    app: web-flask
spec:
  type: LoadBalancer
  selector:
    env: front-end 
  ports:
  - port: 3000  
    targetPort: 5000
    nodePort: 30036